version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${API_SERVER_PORT:-8080}:${API_SERVER_PORT:-8080}"
      - "127.0.0.1:${GRPC_SERVER_PORT:-50051}:${GRPC_SERVER_PORT:-50051}"
      - "127.0.0.1:${ADMIN_SERVER_PORT:-8081}:${ADMIN_SERVER_PORT:-8081}"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=sferra
      - DB_PASSWORD=sferra_password
      - DB_NAME=sferra_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=sferra
      - RABBITMQ_PASSWORD=sferra_password
      - API_SERVER_PORT=${API_SERVER_PORT:-8080}
      - GRPC_SERVER_PORT=${GRPC_SERVER_PORT:-50051}
      - ADMIN_SERVER_PORT=${ADMIN_SERVER_PORT:-8081}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENV=${SENTRY_ENV:-production}
      - GIN_MODE=${GIN_MODE:-release}
    networks:
      - sferra-network

networks:
  sferra-network:
    name: sferra-cloud_default
    external: true
