version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=sferra
      - DB_PASSWORD=sferra_password
      - DB_NAME=sferra_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=sferra
      - RABBITMQ_PASSWORD=sferra_password
    depends_on:
      - db
      - rabbitmq
    networks:
      - sferra-network

networks:
  sferra-network:
    name: sferra-cloud_default
    external: true
