version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: sferra
      POSTGRES_PASSWORD: sferra_password
      POSTGRES_DB: sferra_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-sferra_minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-sferra_minio_password}
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER:-sferra_minio} ${MINIO_ROOT_PASSWORD:-sferra_minio_password};
      /usr/bin/mc mb myminio/${S3_BUCKET};
      exit 0;
      "

volumes:
  db_data:
  rabbitmq_data:
  minio_data:
