// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/account": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "GetTaskImage information about the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "GetTaskImage Account Info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.AccountInfoResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticate user and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.TokenResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Register a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/recognition_tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List DataRecognitionTasks for the authenticated client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recognition_tasks"
                ],
                "summary": "List DataRecognitionTask",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.DataRecognitionTaskListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new DataRecognitionTask",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recognition_tasks"
                ],
                "summary": "Create DataRecognitionTask",
                "parameters": [
                    {
                        "description": "DataRecognitionTask data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.DataRecognitionTask"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.DataRecognitionTask"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/recognition_tasks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "GetTaskImage a DataRecognitionTask by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recognition_tasks"
                ],
                "summary": "GetTaskImage DataRecognitionTask",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DataRecognitionTask ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.DataRecognitionTask"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update a UpdateDataRecognitionTask by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recognition_tasks"
                ],
                "summary": "Update UpdateDataRecognitionTask",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UpdateDataRecognitionTask ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated DataRecognitionTask",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.DataRecognitionTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.DataRecognitionTask"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a DataRecognitionTask by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recognition_tasks"
                ],
                "summary": "Delete DataRecognitionTask",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DataRecognitionTask ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/recognition-tasks/{task_id}/images/upload": {
            "post": {
                "description": "UploadTaskImage an image to storage",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "UploadTaskImage an image",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Recognition Task ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image file",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/recognition-tasks/{task_id}/images/{image_id}": {
            "get": {
                "description": "GetTaskImage an image by ID",
                "produces": [
                    "image/jpeg",
                    "image/png",
                    "image/gif"
                ],
                "summary": "GetTaskImage an image",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Recognition Task ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Image ID",
                        "name": "image_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_bazilio91_sferra-cloud_pkg_proto.Assortment": {
            "type": "object",
            "properties": {
                "chemical_composition": {
                    "type": "string"
                },
                "chemical_gost": {
                    "type": "string"
                },
                "field_status": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.FieldStatus"
                    }
                },
                "figure_type": {
                    "type": "string"
                },
                "form_gost": {
                    "type": "string"
                },
                "material": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "$ref": "#/definitions/types.Any"
                },
                "sub_type": {
                    "type": "string"
                }
            }
        },
        "github_com_bazilio91_sferra-cloud_pkg_proto.Client": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "inn": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ogrn": {
                    "type": "string"
                },
                "owner_fio": {
                    "type": "string"
                },
                "quota": {
                    "type": "integer"
                },
                "total_quota": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.ClientUser"
                    }
                }
            }
        },
        "github_com_bazilio91_sferra-cloud_pkg_proto.ClientUser": {
            "type": "object",
            "properties": {
                "client": {
                    "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.Client"
                },
                "client_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_bazilio91_sferra-cloud_pkg_proto.DataRecognitionTask": {
            "type": "object",
            "properties": {
                "client": {
                    "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.Client"
                },
                "created_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "error": {
                    "type": "string"
                },
                "frontend_result": {
                    "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.TreeNode"
                },
                "frontend_result_unrecognized": {
                    "$ref": "#/definitions/types.JSONValue"
                },
                "id": {
                    "type": "string"
                },
                "processed_images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "recognition_result": {
                    "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.TreeNode"
                },
                "source_images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.Status"
                },
                "status_text": {
                    "type": "string"
                },
                "updated_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "worker_id": {
                    "type": "string"
                }
            }
        },
        "github_com_bazilio91_sferra-cloud_pkg_proto.FieldStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "FieldStatus_FIELD_STATUS_UNSPECIFIED",
                "FieldStatus_OK",
                "FieldStatus_YELLOW"
            ]
        },
        "github_com_bazilio91_sferra-cloud_pkg_proto.Figure": {
            "type": "object",
            "properties": {
                "assortment": {
                    "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.Assortment"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "image_id": {
                    "type": "string"
                },
                "mainSize": {
                    "description": "Types that are valid to be assigned to MainSize:\n\n\t*Figure_MainSizeFloat\n\t*Figure_MainSizeStr"
                },
                "mass": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "size_horizontal": {
                    "type": "number"
                },
                "size_vertical": {
                    "type": "number"
                }
            }
        },
        "github_com_bazilio91_sferra-cloud_pkg_proto.SpecificationRow": {
            "type": "object",
            "properties": {
                "assortment": {
                    "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.Assortment"
                },
                "count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "image_id": {
                    "type": "string"
                },
                "material": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "sb_number": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "size_h": {
                    "type": "string"
                },
                "size_v": {
                    "type": "string"
                }
            }
        },
        "github_com_bazilio91_sferra-cloud_pkg_proto.Status": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13
            ],
            "x-enum-varnames": [
                "Status_STATUS_CREATED",
                "Status_STATUS_READY_FOR_PROCESSING",
                "Status_STATUS_IMAGES_PENDING",
                "Status_STATUS_IMAGES_PROCESSING",
                "Status_STATUS_IMAGES_COMPLETED",
                "Status_STATUS_IMAGES_FAILED_QUOTA",
                "Status_STATUS_IMAGES_FAILED_PROCESSING",
                "Status_STATUS_IMAGES_FAILED_TIMEOUT",
                "Status_STATUS_RECOGNITION_PENDING",
                "Status_STATUS_RECOGNITION_PROCESSING",
                "Status_STATUS_RECOGNITION_COMPLETED",
                "Status_STATUS_RECOGNITION_FAILED_QUOTA",
                "Status_STATUS_RECOGNITION_FAILED_PROCESSING",
                "Status_STATUS_RECOGNITION_FAILED_TIMEOUT"
            ]
        },
        "github_com_bazilio91_sferra-cloud_pkg_proto.TreeNode": {
            "type": "object",
            "properties": {
                "accumulated_count": {
                    "type": "integer"
                },
                "count": {
                    "type": "integer"
                },
                "figure": {
                    "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.Figure"
                },
                "id": {
                    "type": "string"
                },
                "leaves": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.TreeNode"
                    }
                },
                "material": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "spec": {
                    "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.SpecificationRow"
                }
            }
        },
        "pkg_api_handlers.AccountInfoResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.ClientUser"
                }
            }
        },
        "pkg_api_handlers.DataRecognitionTaskListResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_bazilio91_sferra-cloud_pkg_proto.DataRecognitionTask"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "pkg_api_handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "pkg_api_handlers.LoginInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "pkg_api_handlers.RegisterInput": {
            "type": "object",
            "required": [
                "clientID",
                "email",
                "password"
            ],
            "properties": {
                "clientID": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "pkg_api_handlers.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "pkg_api_handlers.TokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "timestamppb.Timestamp": {
            "type": "object",
            "properties": {
                "nanos": {
                    "description": "Non-negative fractions of a second at nanosecond resolution. Negative\nsecond values with fractions must still have non-negative nanos values\nthat count forward in time. Must be from 0 to 999,999,999\ninclusive.",
                    "type": "integer"
                },
                "seconds": {
                    "description": "Represents seconds of UTC time since Unix epoch\n1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to\n9999-12-31T23:59:59Z inclusive.",
                    "type": "integer"
                }
            }
        },
        "types.Any": {
            "type": "object",
            "properties": {
                "type_url": {
                    "description": "A URL/resource name that uniquely identifies the type of the serialized\nprotocol buffer message. This string must contain at least\none \"/\" character. The last segment of the URL's path must represent\nthe fully qualified name of the type (as in\n` + "`" + `path/google.protobuf.Duration` + "`" + `). The name should be in a canonical form\n(e.g., leading \".\" is not accepted).\n\nIn practice, teams usually precompile into the binary all types that they\nexpect it to use in the context of Any. However, for URLs which use the\nscheme ` + "`" + `http` + "`" + `, ` + "`" + `https` + "`" + `, or no scheme, one can optionally set up a type\nserver that maps type URLs to message definitions as follows:\n\n  - If no scheme is provided, ` + "`" + `https` + "`" + ` is assumed.\n  - An HTTP GET on the URL must yield a [google.protobuf.Type][]\n    value in binary format, or produce an error.\n  - Applications are allowed to cache lookup results based on the\n    URL, or have them precompiled into a binary to avoid any\n    lookup. Therefore, binary compatibility needs to be preserved\n    on changes to types. (Use versioned type names to manage\n    breaking changes.)\n\nNote: this functionality is not currently available in the official\nprotobuf release, and it is not used for type URLs beginning with\ntype.googleapis.com.\n\nSchemes other than ` + "`" + `http` + "`" + `, ` + "`" + `https` + "`" + ` (or the empty scheme) might be\nused with implementation specific semantics.",
                    "type": "string"
                },
                "value": {
                    "description": "Must be a valid serialized protocol buffer of the above specified type.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "types.JSONValue": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
